name = "esa-ogp-preview"
main = "src/index.tsx"
compatibility_date = "2025-01-23"
compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

[browser]
binding = "esa_ogp_preview_browser"

[[kv_namespaces]]
binding = "esa_ogp_preview_svg_cache"
id = "ee7d19e651114cd29f2e04bbb3c85c2c"
preview_id = "e082dfde5a8b40c1b1330bd35434c616"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
